name: Build, Linting and Tests
on:
  push:
    branches: ["main"]
  pull_request:

jobs: 
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: sudo apt install libolm-dev
      - run: python -m pip install .[dev]
      - run: tox -e check_types
      - run: tox -e check_codestyle
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: checks
    steps:
       - name: Checkout clean copy
         uses: actions/checkout@v3
       - name: Login to registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Work out labels
         id: meta
         uses: docker/metadata-action@v1
         with: 
           images: ghcr.io/${{ github.repository }}

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6

       - name: Build and push docker image
         uses: docker/build-push-action@v2
         with:
           context: .
           platforms: linux/amd64,linux/arm64
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
