name: Linting and Tests
on:
  push:
    branches: ["main"]
  pull_request:

jobs: 
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: apt install --yes libgraphviz-dev
      - run: python -m pip install flake8 isort
      - run: scripts-dev/lint.sh
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: apt install --yes libgraphviz-dev
      - run: python -m pip install tox
      - run: tox -e check_types
      - run: tox -e check_codestyle
      - run: tox -e py

